.PHONY: build translations clean test web windows windows-deploy windows-zip windows-installer regen-icons linux-appimage linux-tar

# Number of CPU cores for parallel build
NPROCS := $(shell nproc)

# MXE build type: shared (default) or static
# Override with: make windows MXE_BUILD_TYPE=static
MXE_BUILD_TYPE ?= shared

build: translations
	@echo "Building ClipLLM..."
	@mkdir -p build
	@cd build && cmake ..
	@cd build && make -j$(NPROCS)
	@echo ""
	@echo "Build complete. Binary info:"
	@ls -lh build/ClipLLM

translations:
	@echo "Updating translations..."
	@./update-translations.sh

web:
	@echo "Building web page..."
	@VERSION=$$(grep "^project(ClipLLM VERSION" CMakeLists.txt | sed 's/project(ClipLLM VERSION \([0-9.]*\).*/\1/'); \
		cp art/clipllm_hires.png docs/ && \
		echo "<!-- DO NOT EDIT THIS FILE DIRECTLY! It is auto-generated from docs/index.html.in by 'make web' -->" > docs/index.html && \
		sed "s/@VERSION@/$$VERSION/g" docs/index.html.in >> docs/index.html && \
		echo "Web page generated with version $$VERSION"

clean:
	@echo "Cleaning build directories..."
	@rm -rf build build-windows deploy-windows deploy-linux AppDir dist

# Force regeneration of tray icons from art/clipllm_hires.png
# Use this after replacing the source image
regen-icons:
	@echo "Regenerating tray icons from art/clipllm_hires.png..."
	@rm -f resources/icons/tray-icon-*.png resources/icons/tray-icon.ico
	@$(MAKE) build

test:
	@echo "Running tests..."
	@cd build && ctest --output-on-failure

# =============================================================================
# Windows cross-compilation targets
# =============================================================================

# Check if MXE is installed (checks for static or shared compiler)
check-mxe:
	@if [ "$(MXE_BUILD_TYPE)" = "shared" ]; then \
		which $${HOME}/mxe/usr/bin/x86_64-w64-mingw32.shared-gcc >/dev/null 2>&1 || \
			(echo "MXE shared toolchain not found." && \
			 echo "Build with: cd ~/mxe && make -j\$$(nproc) MXE_TARGETS='x86_64-w64-mingw32.shared' qt6" && exit 1); \
	else \
		which $${HOME}/mxe/usr/bin/x86_64-w64-mingw32.static-gcc >/dev/null 2>&1 || \
			(echo "MXE static toolchain not found. Please install MXE first:" && \
			 echo "  git clone https://github.com/mxe/mxe.git ~/mxe" && \
			 echo "  cd ~/mxe" && \
			 echo "  make -j\$$(nproc) MXE_TARGETS='x86_64-w64-mingw32.static' qt6" && exit 1); \
	fi

# problem -- Самый простой и правильный путь: вообще не поддерживать свой toolchain, а использовать MXE wrapper в Makefile
## Build for Windows (cross-compilation with MXE)
## Use static by default, override with: make windows MXE_BUILD_TYPE=shared
#windows: check-mxe translations
#	@echo "Building ClipLLM for Windows (x86_64, $(MXE_BUILD_TYPE))..."
#	@mkdir -p build-windows
#	@cd build-windows && \
#		cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/windows-x86_64-mingw.cmake \
#		      -DCMAKE_BUILD_TYPE=Release \
#		      -DMXE_BUILD_TYPE=$(MXE_BUILD_TYPE) \
#		      .. && \
#		cmake --build . --parallel $(NPROCS)
#	@echo ""
#	@echo "Windows build complete!"
#	@ls -lh build-windows/ClipLLM.exe

windows: check-mxe translations
	@echo "Building ClipLLM for Windows (x86_64, $(MXE_BUILD_TYPE))..."
	@mkdir -p build-windows
	@cd build-windows && \
		$(HOME)/mxe/usr/bin/x86_64-w64-mingw32.$(MXE_BUILD_TYPE)-cmake \
		  -DCMAKE_BUILD_TYPE=Release \
		  .. && \
		cmake --build . --parallel $(NPROCS)


# Deploy Windows build (static builds don't need DLLs)
windows-deploy: windows
	@echo "Deploying Windows build ($(MXE_BUILD_TYPE))..."
	@MXE_BUILD_TYPE=$(MXE_BUILD_TYPE) ./scripts/deploy-windows.sh

# Create Windows ZIP archive
windows-zip: windows-deploy
	@echo "Creating Windows ZIP archive..."
	@mkdir -p dist
	@cd deploy-windows && \
		VERSION=$$(grep "^project(ClipLLM VERSION" ../CMakeLists.txt | sed 's/project(ClipLLM VERSION \([0-9.]*\).*/\1/') && \
		zip -r ../dist/clipllm-$${VERSION}-windows-x86_64.zip . && \
		cd .. && ls -lh dist/clipllm-$${VERSION}-windows-x86_64.zip

# Create Windows installer using NSIS (native Windows installer)
windows-installer: windows-deploy
	@echo "Creating Windows installer using NSIS..."
	@which makensis >/dev/null 2>&1 || { echo "NSIS not found. Install with: sudo apt install nsis"; exit 1; }
	@mkdir -p dist
	@VERSION=$$(grep "^project(ClipLLM VERSION" CMakeLists.txt | sed 's/project(ClipLLM VERSION \([0-9.]*\).*/\1/'); \
		echo "Building installer version $$VERSION..."; \
		makensis -DPRODUCT_VERSION=$$VERSION -NOCD installer/clipllm.nsi && \
		ls -lh dist/ClipLLM-$$VERSION-windows-x86_64-setup.exe

# Quick test with Wine
test-windows-wine: windows-deploy
	@echo "Testing Windows build with Wine..."
	@which wine >/dev/null 2>&1 || (echo "Wine not installed. Install with: sudo apt install wine" && exit 1)
	@wine deploy-windows/ClipLLM.exe --version 2>/dev/null || echo "Note: Full Wine test requires a complete Wine setup"

# =============================================================================
# Linux distribution targets
# =============================================================================

# Create tar.gz archive with portable distribution
linux-tar: build
	@echo "Creating Linux tar.gz archive..."
	@mkdir -p dist
	@rm -rf deploy-linux
	@mkdir -p deploy-linux/clipllm
	@mkdir -p deploy-linux/clipllm/translations
	@mkdir -p deploy-linux/clipllm/share/applications
	@mkdir -p deploy-linux/clipllm/share/icons/hicolor/scalable/apps
	# Copy binary
	@cp build/ClipLLM deploy-linux/clipllm/
	# Copy translations
	@cp build/translations/*.qm deploy-linux/clipllm/translations/ 2>/dev/null || true
	# Copy desktop file with full path for portable use
	@sed 's|Icon=clipllm|Icon=/opt/clipllm/share/icons/hicolor/scalable/apps/clipllm.svg|' \
		resources/clipllm.desktop.in > deploy-linux/clipllm/share/applications/clipllm.desktop
	@sed 's|Exec=clipllm|Exec=/opt/clipllm/ClipLLM|' \
		deploy-linux/clipllm/share/applications/clipllm.desktop > /tmp/clipllm.desktop.tmp && \
		mv /tmp/clipllm.desktop.tmp deploy-linux/clipllm/share/applications/clipllm.desktop
	# Copy icon to proper location
	@cp resources/icons/app-icon.svg deploy-linux/clipllm/share/icons/hicolor/scalable/apps/clipllm.svg
	# Also copy icons to simple icons/ dir for reference
	@mkdir -p deploy-linux/clipllm/icons
	@cp resources/icons/app-icon.svg deploy-linux/clipllm/icons/
	@cp resources/icons/tray-icon-*.png deploy-linux/clipllm/icons/ 2>/dev/null || true
	# Create README
	@echo "# ClipLLM - Portable Linux Distribution" > deploy-linux/clipllm/README.md
	@echo "" >> deploy-linux/clipllm/README.md
	@echo "## Installation" >> deploy-linux/clipllm/README.md
	@echo "1. Copy clipllm/ directory to /opt/clipllm/ (or ~/opt/clipllm/)" >> deploy-linux/clipllm/README.md
	@echo "2. Create symlink: sudo ln -sf /opt/clipllm/ClipLLM /usr/local/bin/clipllm" >> deploy-linux/clipllm/README.md
	@echo "3. Copy desktop file: sudo cp share/applications/clipllm.desktop /usr/share/applications/" >> deploy-linux/clipllm/README.md
	@echo "4. Update icon cache: sudo gtk-update-icon-cache /usr/share/icons/hicolor/" >> deploy-linux/clipllm/README.md
	@echo "" >> deploy-linux/clipllm/README.md
	@echo "## Quick Install (from extracted directory)" >> deploy-linux/clipllm/README.md
	@echo "Run: sudo ./install.sh" >> deploy-linux/clipllm/README.md
	@echo "" >> deploy-linux/clipllm/README.md
	@echo "## Quick Uninstall" >> deploy-linux/clipllm/README.md
	@echo "Run: sudo /opt/clipllm/uninstall.sh" >> deploy-linux/clipllm/README.md
	@echo "" >> deploy-linux/clipllm/README.md
	# Create install script
	@echo "#!/bin/bash" > deploy-linux/clipllm/install.sh
	@echo "set -e" >> deploy-linux/clipllm/install.sh
	@echo "" >> deploy-linux/clipllm/install.sh
	@echo 'INSTALL_DIR="/opt/clipllm"' >> deploy-linux/clipllm/install.sh
	@echo 'SCRIPT_DIR="$$(dirname "$$(readlink -f \"$$0\")")"' >> deploy-linux/clipllm/install.sh
	@echo "" >> deploy-linux/clipllm/install.sh
	@echo 'if [ "$$EUID" -ne 0 ]; then' >> deploy-linux/clipllm/install.sh
	@echo '    echo "Please run as root (sudo ./install.sh)"' >> deploy-linux/clipllm/install.sh
	@echo '    exit 1' >> deploy-linux/clipllm/install.sh
	@echo 'fi' >> deploy-linux/clipllm/install.sh
	@echo "" >> deploy-linux/clipllm/install.sh
	@echo "# Copy files to install directory" >> deploy-linux/clipllm/install.sh
	@echo 'mkdir -p $$INSTALL_DIR' >> deploy-linux/clipllm/install.sh
	@echo 'cp -r . $$INSTALL_DIR/' >> deploy-linux/clipllm/install.sh
	@echo "" >> deploy-linux/clipllm/install.sh
	@echo "# Create symlink in /usr/local/bin" >> deploy-linux/clipllm/install.sh
	@echo 'ln -sf $$INSTALL_DIR/ClipLLM /usr/local/bin/clipllm' >> deploy-linux/clipllm/install.sh
	@echo "" >> deploy-linux/clipllm/install.sh
	@echo "# Install desktop file" >> deploy-linux/clipllm/install.sh
	@echo 'cp $$INSTALL_DIR/share/applications/clipllm.desktop /usr/share/applications/' >> deploy-linux/clipllm/install.sh
	@echo "" >> deploy-linux/clipllm/install.sh
	@echo "# Install icon" >> deploy-linux/clipllm/install.sh
	@echo "mkdir -p /usr/share/icons/hicolor/scalable/apps" >> deploy-linux/clipllm/install.sh
	@echo 'cp $$INSTALL_DIR/share/icons/hicolor/scalable/apps/clipllm.svg /usr/share/icons/hicolor/scalable/apps/' >> deploy-linux/clipllm/install.sh
	@echo "gtk-update-icon-cache /usr/share/icons/hicolor/ 2>/dev/null || true" >> deploy-linux/clipllm/install.sh
	@echo "" >> deploy-linux/clipllm/install.sh
	@echo "echo \"ClipLLM installed successfully!\"" >> deploy-linux/clipllm/install.sh
	@echo "echo \"Run 'clipllm' to start the application\"" >> deploy-linux/clipllm/install.sh
	@chmod +x deploy-linux/clipllm/install.sh
	# Create uninstall script
	@echo "#!/bin/bash" > deploy-linux/clipllm/uninstall.sh
	@echo "set -e" >> deploy-linux/clipllm/uninstall.sh
	@echo "" >> deploy-linux/clipllm/uninstall.sh
	@echo 'INSTALL_DIR="/opt/clipllm"' >> deploy-linux/clipllm/uninstall.sh
	@echo "" >> deploy-linux/clipllm/uninstall.sh
	@echo 'if [ "$$EUID" -ne 0 ]; then' >> deploy-linux/clipllm/uninstall.sh
	@echo '    echo "Please run as root (sudo $$0)"' >> deploy-linux/clipllm/uninstall.sh
	@echo '    exit 1' >> deploy-linux/clipllm/uninstall.sh
	@echo 'fi' >> deploy-linux/clipllm/uninstall.sh
	@echo "" >> deploy-linux/clipllm/uninstall.sh
	@echo 'echo "Uninstalling ClipLLM..."' >> deploy-linux/clipllm/uninstall.sh
	@echo "rm -f /usr/local/bin/clipllm" >> deploy-linux/clipllm/uninstall.sh
	@echo "rm -f /usr/share/applications/clipllm.desktop" >> deploy-linux/clipllm/uninstall.sh
	@echo "rm -f /usr/share/icons/hicolor/scalable/apps/clipllm.svg" >> deploy-linux/clipllm/uninstall.sh
	@echo "gtk-update-icon-cache /usr/share/icons/hicolor/ 2>/dev/null || true" >> deploy-linux/clipllm/uninstall.sh
	@echo 'rm -rf $$INSTALL_DIR' >> deploy-linux/clipllm/uninstall.sh
	@echo 'echo "ClipLLM uninstalled successfully!"' >> deploy-linux/clipllm/uninstall.sh
	@chmod +x deploy-linux/clipllm/uninstall.sh
	@echo "" >> deploy-linux/clipllm/README.md
	@echo "## Requirements" >> deploy-linux/clipllm/README.md
	@echo "- Qt6 (qt6-base, qt6-svg)" >> deploy-linux/clipllm/README.md
	@echo "- X11 or Wayland" >> deploy-linux/clipllm/README.md
	@VERSION=$$(grep "^project(ClipLLM VERSION" CMakeLists.txt | sed 's/project(ClipLLM VERSION \([0-9.]*\).*/\1/'); \
		tar -czf dist/clipllm-$${VERSION}-linux-x86_64.tar.gz -C deploy-linux clipllm && \
		ls -lh dist/clipllm-$${VERSION}-linux-x86_64.tar.gz

# Create AppImage (requires linuxdeploy)
linux-appimage: build
	@echo "Creating AppImage..."
	@which linuxdeploy >/dev/null 2>&1 || { echo "linuxdeploy not found. Download from https://github.com/linuxdeploy/linuxdeploy/releases"; exit 1; }
	@mkdir -p dist
	@rm -rf AppDir
	@mkdir -p AppDir/usr/bin
	@mkdir -p AppDir/usr/share/applications
	@mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps
	@mkdir -p AppDir/usr/share/metainfo
	# Copy binary
	@cp build/ClipLLM AppDir/usr/bin/clipllm
	# Copy desktop file
	@sed 's/Exec=clipllm/Exec=clipllm/' resources/clipllm.desktop.in > AppDir/usr/share/applications/clipllm.desktop
	# Copy icon
	@cp resources/icons/app-icon.svg AppDir/usr/share/icons/hicolor/scalable/apps/clipllm.svg
	# Copy translations
	@mkdir -p AppDir/usr/share/clipllm/translations
	@cp build/translations/*.qm AppDir/usr/share/clipllm/translations/ 2>/dev/null || true
	# Run linuxdeploy
	@linuxdeploy --appdir AppDir --output appimage
	@VERSION=$$(grep "^project(ClipLLM VERSION" CMakeLists.txt | sed 's/project(ClipLLM VERSION \([0-9.]*\).*/\1/'); \
		mv ClipLLM-x86_64.AppImage dist/clipllm-$${VERSION}-linux-x86_64.AppImage && \
		ls -lh dist/clipllm-$${VERSION}-linux-x86_64.AppImage
